# Generated by Django 2.1.7 on 2019-02-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='书名')),
                ('date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('wordsCount', models.IntegerField(blank=True, null=True, verbose_name='字数统计')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='书籍价格')),
                ('series', models.CharField(blank=True, max_length=250, null=True, verbose_name='系列')),
                ('size', models.CharField(max_length=250, verbose_name='尺寸')),
                ('pages', models.IntegerField(verbose_name='页码数')),
                ('turn', models.CharField(blank=True, max_length=90, null=True, verbose_name='版次')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('isbn', models.CharField(max_length=90, verbose_name='ISBN')),
                ('catalog', models.TextField(blank=True, null=True, verbose_name='目录')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=250, verbose_name='分类')),
            ],
            options={
                'verbose_name': '种类',
                'db_table': 'kind',
                'verbose_name_plural': '种类',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
            ],
            options={
                'verbose_name': '出版社',
                'db_table': 'publisher',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('translator', models.CharField(max_length=100, verbose_name='译者')),
            ],
            options={
                'verbose_name': '译者',
                'db_table': 'Translator',
                'verbose_name_plural': '译者',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=100, verbose_name='作者')),
            ],
            options={
                'verbose_name': '作者',
                'db_table': 'writer',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='kind',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookM.Kind'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookM.Publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookM.Translator'),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookM.Writer'),
        ),
    ]
